services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - app_network
    depends_on:
      - backend

  backend:
    build: ./backend
    environment:
      - FRONTEND_URL=http://frontend:80
    networks:
      - app_network

  prometheus:
    image: prom/prometheus:main@sha256:71d3894cc4cc1e2f460af4a3a9016cebf8037061f5a4ee324b6414c775de55fb
    expose:
      - 9090
    networks:
      - app_network
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"

networks:
  app_network:
    driver: bridge
